###########################################################
### 基本配置
###########################################################

# 网站标题
title: 董金成的个人空间

# 作者信息
author: 董金成

# 网站描述（SEO用）
description: "董金成的个人网站 | 技术博客 | 学术分享"

###############################################
### 导航栏配置
###############################################

navbar-links:
  首页: "/"
  博客: "blog"
  项目: "projects"
  关于我: "aboutme"
  资源:
    - GitHub: "https://github.com/yourusername"
    - 论文: "publications"

################
### 头像/Logo
################

# 导航栏头像
avatar: "/assets/img/profile.jpg"  # 请替换为你的头像路径
round-avatar: true

#####################################
### 社交媒体链接 (页脚显示)
#####################################

social-network-links:
  email: "your.email@example.com"
  github: yourusername
  linkedin: yourprofile
  google-scholar: "your_gs_id"
  twitter: yourhandle
  #wechat: "/assets/img/wechat-qr.jpg"  # 微信二维码图片

# RSS订阅配置
rss-description: "董金成的技术博客更新"

######################################
### 颜色和外观配置
######################################

# 配色方案
page-col: "#FFFFFF"       # 页面背景
text-col: "#333333"       # 正文文字
link-col: "#2a7ae2"       # 链接颜色
hover-col: "#1756a9"      # 鼠标悬停
navbar-col: "#f8f9fa"     # 导航栏背景
navbar-text-col: "#333333" # 导航栏文字
footer-col: "#f8f9fa"     # 页脚背景
footer-text-col: "#666666" # 页脚文字

#################################
### 功能配置
#################################

# 每页显示文章数
paginate: 8

# 文章摘要设置
excerpt_length: 100
feed_show_excerpt: true
feed_show_tags: true

# 日期格式
date_format: "%Y年%-m月%-d日"

# 启用搜索功能
post_search: true

# 启用"编辑此页"按钮
edit_page_button: true

#################################
### 评论系统 (选择一种)
#################################

# Disqus评论
# disqus: "yourdisqusshortname"

# Utterances (基于GitHub Issues)
utterances:
  repository: yourgithub/yourrepo  # 替换为你的仓库
  issue-term: pathname
  theme: github-light
  label: blog-comments

#################################
### 分析统计
#################################

# Google Analytics 4
gtag: "G-XXXXXXXXXX"  # 替换为你的GA4 ID

################################
### 高级设置 (一般无需修改)
################################

# Jekyll基础配置
timezone: "Asia/Shanghai"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 默认布局设置
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

# 排除文件
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
